/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pielot_openal_OpenAlBridge */

#ifndef _Included_org_pielot_openal_OpenAlBridge
#define _Included_org_pielot_openal_OpenAlBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef org_pielot_openal_OpenAlBridge_SUCCESS
#define org_pielot_openal_OpenAlBridge_SUCCESS 1L
#undef org_pielot_openal_OpenAlBridge_ERROR
#define org_pielot_openal_OpenAlBridge_ERROR 0L
/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_init
  (JNIEnv *, jclass);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_close
  (JNIEnv *, jclass);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    addBuffer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_addBuffer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    releaseBuffer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_releaseBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    addSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_addSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    releaseSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_releaseSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    setPosition
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_pielot_openal_OpenAlBridge_setPosition
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    setPitch
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_pielot_openal_OpenAlBridge_setPitch
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    setGain
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_pielot_openal_OpenAlBridge_setGain
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    setRolloffFactor
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_pielot_openal_OpenAlBridge_setRolloffFactor
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    play
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_play
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    stop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    setListenerPos
 * Signature: (FFF)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_setListenerPos
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_pielot_openal_OpenAlBridge
 * Method:    setListenerOrientation
 * Signature: (FFF)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_openal_OpenAlBridge_setListenerOrientation
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
